"""Retirando o admin do usuario.

Revision ID: b924a108cb84
Revises: 54b36023c79c
Create Date: 2026-04-01 23:01:22.601530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b924a108cb84'
down_revision: Union[str, Sequence[str], None] = '54b36023c79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
